steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-boilerplate/fastapi-boilerplate:$SHORT_SHA',
      '.'
    ]

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-boilerplate/fastapi-boilerplate:$SHORT_SHA'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fastapi-boilerplate
      - --image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-boilerplate/fastapi-boilerplate:$SHORT_SHA
      - --region=asia-southeast1
      - --platform=managed
      - --quiet

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-boilerplate/fastapi-boilerplate:$SHORT_SHA'
